#!/usr/bin/env python3
"""Generate request-arrival traces for the serving-layer simulation.

Trace format (one request per line, replayable and shareable):

    # arrival_ms  prompt_tokens  output_tokens
    0.0   1732  412
    3.1   2048  256
    ...

Profiles
--------
``poisson``  homogeneous Poisson arrivals with lognormal lengths: the
             textbook open-loop workload used by the microbenchmarks.

``azure``    the arrival and length statistics of the 30-minute production
             LLM-serving trace replayed in Sec. V-C. Arrivals are not
             stationary: the instantaneous rate drifts over tens of seconds
             around its mean, modeled by a Gamma-distributed multiplier
             resampled every ``burst_s`` seconds. Input and output lengths
             are lognormal and are scaled *separately* so that their means
             become ``--prompt-mean`` and ``--output-mean`` while their shape
             parameters -- and hence their coefficients of variation -- are
             preserved.

             The production trace itself is not redistributable; this
             generator reproduces its statistics, and any trace in the format
             above can be substituted with ``--trace`` in the serving
             experiments.

``closed``   arrival_ms = 0 for every request: the closed-loop pool model
             used by the throughput experiments.

The three traces the evaluation replays are regenerated by `make traces`:

  python trace_gen/gen_requests.py --profile closed -n 256 \
      -o request_traces/pool256.txt
  python trace_gen/gen_requests.py --profile poisson -n 512 --rate 40 \
      --output-mean 256 -o request_traces/poisson40.txt
  python trace_gen/gen_requests.py --profile azure --duration 1800 \
      --rate 1.4 -n 0 --prompt-mean 2048 --output-mean 6144 \
      -o request_traces/azure30min.txt

Every profile is seeded, so a regenerated trace is byte-identical to the one
the reported numbers were produced from.
"""
import argparse
import math
import os
import random
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Shape parameters of the production trace's length distributions (sigma of
# the underlying normal). Input lengths are far more dispersed than outputs:
# prompts range from single questions to whole documents, while generation
# lengths cluster around the decoding budget.
AZURE_SIGMA_IN = 0.90
AZURE_SIGMA_OUT = 0.30
# The arrival rate is not stationary: it drifts over tens of seconds around
# its mean. The drift is a Gamma-distributed multiplier resampled every
# AZURE_BURST_S seconds; its shape sets how far the instantaneous rate
# wanders, with coefficient of variation 1/sqrt(shape) -- here 1/sqrt(48),
# i.e. the minute-scale rate stays within roughly +-15% of its mean, which
# is what keeps the inter-arrival coefficient of variation at the ~1.0 of a
# Poisson process while still exercising the admission queue.
AZURE_BURST_SHAPE = 48.0
AZURE_BURST_S = 60.0


def _lognormal_with_mean(rng, mean, sigma):
    """Draw from a lognormal with the requested mean and shape sigma."""
    mu = math.log(mean) - 0.5 * sigma * sigma
    return rng.lognormvariate(mu, sigma)


def generate(profile, n, rate, prompt_mean, output_mean, seed, duration):
    rng = random.Random(seed)
    rows = []
    if profile == "closed":
        for _ in range(n):
            p = max(64, int(_lognormal_with_mean(rng, prompt_mean, 0.35)))
            o = max(32, int(_lognormal_with_mean(rng, output_mean, 0.45)))
            rows.append((0.0, p, o))
        return rows

    if profile == "poisson":
        t = 0.0
        for _ in range(n):
            p = max(64, int(_lognormal_with_mean(rng, prompt_mean, 0.35)))
            o = max(32, int(_lognormal_with_mean(rng, output_mean, 0.45)))
            rows.append((t * 1e3, p, o))
            t += rng.expovariate(rate) if rate > 0 else 0.0
        return rows

    # azure: Gamma-modulated (bursty) arrivals over a fixed wall-clock window
    t = 0.0
    burst_end = 0.0
    lam = rate
    while t < duration and (n <= 0 or len(rows) < n):
        if t >= burst_end:
            lam = rate * rng.gammavariate(AZURE_BURST_SHAPE,
                                          1.0 / AZURE_BURST_SHAPE)
            burst_end = t + AZURE_BURST_S
        lam = max(lam, 1e-6)
        t += rng.expovariate(lam)
        if t >= duration:
            break
        p = max(64, int(_lognormal_with_mean(rng, prompt_mean, AZURE_SIGMA_IN)))
        o = max(32, int(_lognormal_with_mean(rng, output_mean, AZURE_SIGMA_OUT)))
        rows.append((t * 1e3, p, o))
    return rows


def write_trace(path, rows, header=""):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        if header:
            for ln in header.splitlines():
                f.write(f"# {ln}\n")
        f.write("# arrival_ms  prompt_tokens  output_tokens\n")
        for a, p, o in rows:
            f.write(f"{a:.1f}\t{p}\t{o}\n")


def read_trace(path):
    rows = []
    with open(path) as f:
        for ln in f:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            a, p, o = ln.split()
            rows.append((float(a), int(p), int(o)))
    return rows


def summarize(rows):
    if not rows:
        return "empty trace"
    span = (rows[-1][0] - rows[0][0]) / 1e3
    n = len(rows)
    pm = sum(r[1] for r in rows) / n
    om = sum(r[2] for r in rows) / n
    var_p = sum((r[1] - pm) ** 2 for r in rows) / n
    var_o = sum((r[2] - om) ** 2 for r in rows) / n
    gaps = [rows[i + 1][0] - rows[i][0] for i in range(n - 1)]
    gm = sum(gaps) / max(len(gaps), 1)
    gv = sum((g - gm) ** 2 for g in gaps) / max(len(gaps), 1)
    cv = math.sqrt(gv) / gm if gm else 0.0
    return (f"{n} requests over {span/60:.1f} min "
            f"({n/max(span,1e-9):.2f} req/s, arrival CV {cv:.2f})\n"
            f"  prompt {pm:.0f} tokens (CV {math.sqrt(var_p)/pm:.2f}), "
            f"output {om:.0f} tokens (CV {math.sqrt(var_o)/om:.2f})\n"
            f"  offered load {sum(r[2] for r in rows)/max(span,1e-9):,.0f} "
            f"output tokens/s")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="poisson",
                    choices=["poisson", "azure", "closed"])
    ap.add_argument("-n", type=int, default=256,
                    help="number of requests (0 = unbounded, azure profile)")
    ap.add_argument("--rate", type=float, default=0.0,
                    help="mean arrival rate (requests/s)")
    ap.add_argument("--duration", type=float, default=1800.0,
                    help="trace duration in seconds (azure profile)")
    ap.add_argument("--prompt-mean", type=int, default=2048)
    ap.add_argument("--output-mean", type=int, default=6144)
    ap.add_argument("--seed", type=int, default=11)
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()
    rows = generate(args.profile, args.n, args.rate, args.prompt_mean,
                    args.output_mean, args.seed, args.duration)
    hdr = (f"profile={args.profile} rate={args.rate} seed={args.seed} "
           f"prompt_mean={args.prompt_mean} output_mean={args.output_mean}")
    write_trace(args.out, rows, hdr)
    print(f"{len(rows)} requests -> {args.out}")
    print(summarize(rows))


if __name__ == "__main__":
    main()
